### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/classes#4]
Top priority
-------------------

- [ ] All: Change lectures table: Topic, Description, REsources, Length, ID
  - [ ] All: including what is in the unreleased lectures
  - [ ] All: in unreleased lectures, correct 'slides' to 'video' where appropriate
- [ ] (Jerome) Record paper1 video
- [ ] (Dimitar) prepare Python tutorial for Monday (link to eve as an example of what can be done in Python)
- [x] (Dimitar) Email students about how to use the refs.bib file.
- [x] (Dimitar) Email students that we can help them with committing their homework during Monday's lecture.
- [ ] (Vibhatha) Install Ubuntu on Virtual Box and Guest addition
- [ ] (Tony, Miao) prepare tutorial on Github for Monday

- [ ] Verify all the links in theory lectures go to youtube or correct box
- [ ] Publish lessons to students
- [ ] Miao & Jerome: fix slides in offixe mix, due Tue, Jan 17
- [x] Badi copy all office mix slides into folder all of us have access to
- [x] Dimitar: Create paper-1 assignment
- [ ] Miao & Jerome: class video for Monday (change and reapply theme: background & slide position)
- [ ] Tony and Dimitar: documentation and example on cluster command for Mark and other students (installing cloudmesh).
- [ ] Jerome: notify all students in CANVAS that are not on piazza on that class started they need to join piazza.
- [x] Tony organizes
   - [X] Who is expert for OSx: Tony
   - [x] Who is expert for Windows 10: Vibatha and Jerome
   - [X] Who is expert for Ubuntu: Dimitar, Miao, Tony, Vibatha
- [X] Vibhatha: bash on Windows, 17, January.
   - [x] Windows-bash rst file was added
   - [ ] Linking to web page
- [X] Vibhatha Installed Cloudmesh
     - [ ] Install Hadoop using cloudmesh
     - [ ] Install Spark using cloudmesh

- [ ] Post AIs' emails and IDs on class website/Piazza
- [ ] Post office hour on class website/Piazza
- [ ] Cloudmesh lectures
- [ ] Crash course on Python
- [ ] Crash course on Bash

New
-----

- [ ] complete bibtex for latex.rst: 
   - [ ] LaTeX Users and Reference Guide, by Leslie Lamport ; 
   - [ ] LaTeX an Introduction, by Helmut Kopka; 
   - [ ] The LaTeX Companion, by Frank Mittelbach
   - [ ] Refernve manual
   - [ ] not so short introduction
Priority
-------------------
- [ ] badi: cleanup cluster command
- [ ] make sure the cluster command works on AWS and azure

Overdue
---------
- [x] Mon, Jan 16. Tony: Reclarification: A single TA collects all contact addresses of all TAS and sends single email to gregor. preferably this e-mail has an vcard attachment for each student so i can just click on the vcard so its added to my contact. Typically you can add yourself to your own contcats program and than export the vcard. On OSX it works like that.
- [x] Fri, Jan 20. Tony verifies and organizes All Tas: do pull request of class and add/update resume and picture
- [x] Fri, Jan 13. Identify 2 TAs that do Windows 10 support and run Windows 10 on their machines. Vibhatha & ?.
- [x] Jan 10: TAs identify office hours. Add to calendar Dimitar created: due Jan 10
- [ ] Jerome: Jan 16: google spreadsheet, create scripts so we can merge spread sheets e.g. download
   CANVAS gradebook, download google spreadsheed compare. develop script such as 
   
   i524-compare --canvas canvas.csv --google google.csv

   returns list such as

   Gregor von Laszewski, HID xyz, project is no longer found in CANVAS

   googlespread sheet gets column "enrolled" in which you mark all students that you found in
   canvas as enroled in spreadsheet. You must not remove them from google so we can identify how
   unenrolled and notify university, which is required from us.

   so we need option --update-enrollment so you do not have to do that by hand.
   use docopts to manage parameters

   due date Jan:10

   check into bin dir of classes. 

TA test
-------

On Friday 11am I will test all TAs for their setup of python on their Laptops. THis includes
proper setup of python 2.7.13, virtualenv, pip, coudmesh install, editor for python (pycharm)
We recommend for class ubuntu if linux. if windows, this is done in virtualbox. 
PS: if you run anything else than ubuntu its yor buisiness, you need to help people in ubuntu. If students run anything else than ubuntu its their buisiness.
However we need 1 - 2 TAs that do support while running Windows 10.

Unassigned, Due Mon, Jan 16
------------
- [ ] TAs Make sure you understand pip virtualenv
- [ ] TAs identify at least 10 hours after hour support
- [ ] TAs identify ansible project for you 
- [ ] TAs decide if you like to contribute on a paper (non paid)
- [x] TAs add more tasks here that were comming form initial meeting that Dimitar  kept notes for
- [ ] looks like a company found this, so we may want to consider to see if something like this is useful for futuresystems. we may actually have this already: http://futuregrid.github.io/manual/horizon.html http://cloudmesh.github.io/introduction_to_cloud_computing/
- [ ] Everybody gets familiar with pull request on classes https://help.github.com/articles/creating-a-pull-request/
- [x] work on https://cloudmesh.github.io/classes/todo.html

Jerome
--------
- [x] Jerome: creates Google spreadsheet with HIDs
- [x] Jerome: replicates google quiz from I523 on canvas for I524 (deadline Tuesday). Do not make public before Gregor and badi have not reviewed.

Vibatha
--------
- [x] Vibatha: Learn how to do pull reuests
- [x] Vibatha: Document pull request for technology homework. Talk to Gregor and Badi as needed

Miao
-----
- [x] Miao: get access to piazza
- [x] Miao: catch up with the meeting we had Friday

Dimitar
-------
- [x] Dimitar: distribute meeting notes

Resolved
----------
Move all resolved items after a week or so here so we have a record of it and keep the list above small

- [x] Jan 10 Dimitar create split video code, check into bin dir of classes use docopts for parameters and manual
- [x] Jan 10 Dimitar place videos in onedrive 
- [x] Jan 10 Dimitar  create calendar of when you WORK on class, must cover 20 hours. 
   2 hours of them need to be available for a weekly meeting all attend 
   sometime between Tuesday - Friday 10 - 2pm
- [x] Jan 10 Gregor get videos, post in youtube
- [x] Jan 10 Gregor make announcement on piazza for online students. Latest Jan 11
- [x] Jan 11: Gregor add posted lecture to lectures.rst

- [x] Jan 10: Vibatha lead, all TAs create account on github. Must use git config, i think we have this as youtube and already in lessons. Vibhatha does it wrong. Jan 10
- [x] Jan10: Gregor: post survey links on piazza

- [x] Jerome: Generate HIDs.
- [x] Gregor originally Jerome: Announce HIDs to students on Piazza, due Fri, Jan 13.
  - [x] Gregor/Dimitar originally Jerome: make sure HIDs are explained on website. Due Fri, Jan 13.
- [x] Dimitar: assignment of TechList <> HIDs, due Fri, Jan 13.
  - [x] Dimitar: announce on Piazza, due Fri, Jan 13.
- [x] Gregor originally Miao: video for TechList, due Mon, Jan 16.
- [x] single meeting time this friday 11am. All TAs must be present
- [x] weekly meeting time Tuesday all TAs must be present
- [x] Vibhatha: doodle for fixed meeting times for online class support, due Fri, Jan 13
  - [x] Vibhatha: post announcement on Piazza and update website

**Comment by badi** [comment]
I'm closing this as they've been filed as separate issues:

#117 
#118
#119 
#120
#121
#122
#123
#124
#125
#126
#127
#128
#129
#130
#131
#132
#133
#134
#135
